version: 2.1

orbs:
  orbtools: gofunky/orbtools@0.3.2
  envorb: gofunky/envorb@0.3.9
  docker: gofunky/docker@0.1.2
  readmyhub: gofunky/readmyhub@1.2.2

master_filter: &master_filter
  filters:
    branches:
      only:
        - master

tag_filter: &tag_filter
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

pr_filter: &pr_filter
  filters:
    branches:
      ignore:
        - master

use_alpine_version: &use_alpine_version
  alpine_version: "3.8"

set_compose_version: &set_compose_version
  attach: true
  <<: *use_alpine_version
  variable: COMPOSE_VERSION
  prepare:
    - run:
        name: Install docker-compose
        command: |
          echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories
          echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
          echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
          apk upgrade --no-cache --available
          apk add --no-cache docker-compose
  cmd: docker-compose version

set_docker_version: &set_docker_version
  <<: *use_alpine_version
  variable: DOCKER_VERSION
  repository: "docker/docker-ce"

docker_job: &docker_job
  attach: true
  base_tag: funkydocker
  add_labels: true
  docker_version: 18.09.0
  context: docker-hub
  args: "VERSION=${DOCKER_VERSION},DOCKER=${DOCKER_VERSION}"

workflows:
  readme:
    jobs:
      - readmyhub/update:
          name: update_readme
          <<: *master_filter
          context: docker-hub

  publish_latest_docker:
    jobs:
      - envorb/cmd_version:
          name: set_compose_version
          <<: *set_compose_version

      - envorb/github:
          name: set_docker_version
          <<: *set_docker_version

      - docker/build_test_push:
          name: build_latest_image
          <<: [*master_filter, *docker_job]
          tags: "gofunky/docker:${DOCKER_VERSION},gofunky/docker:${DOCKER_VERSION}-compose${COMPOSE_VERSION},gofunky/docker:latest"
          login: docker login -u $DOCKER_USR -p $DOCKER_PWD
          cache: true
          requires: [set_docker_version, set_compose_version]

      - docker/build_test_push:
          name: build_envload_image
          <<: [*master_filter, *docker_job]
          tags: "gofunky/docker:${DOCKER_VERSION}-envload,gofunky/docker:${DOCKER_VERSION}-compose${COMPOSE_VERSION}-envload,gofunky/docker:envload"
          login: docker login -u $DOCKER_USR -p $DOCKER_PWD
          cache: true
          add_labels: false
          path: "./envorb"
          compose: "./envorb/test/docker-compose.test.yml"
          base_tag: dockertest
          args: "BASE=gofunky/docker:${DOCKER_VERSION}-compose${COMPOSE_VERSION}"
          requires: [set_docker_version, set_compose_version, build_latest_image]

      - docker/build_test:
          name: test_latest
          <<: [*pr_filter, *docker_job]
          tags: "gofunky/docker:${DOCKER_VERSION},gofunky/docker:${DOCKER_VERSION}-compose${COMPOSE_VERSION},gofunky/docker:latest"
          requires: [set_docker_version, set_compose_version]

      - docker/build_test:
          name: test_envload
          <<: [*pr_filter, *docker_job]
          tags: "gofunky/docker:${DOCKER_VERSION}-envload,gofunky/docker:${DOCKER_VERSION}-compose${COMPOSE_VERSION}-envload,gofunky/docker:envload"
          add_labels: false
          path: "./envorb"
          compose: "./envorb/test/docker-compose.test.yml"
          base_tag: dockertest
          args: "BASE=gofunky/docker:${DOCKER_VERSION}-compose${COMPOSE_VERSION}"
          requires: [set_docker_version, set_compose_version, test_latest]

  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          <<: *master_filter
    jobs:
      - envorb/cmd_version:
          name: set_compose_version
          <<: *set_compose_version

      - envorb/github:
          name: set_docker_version
          <<: *set_docker_version

      - docker/build_test_push:
          name: build_latest_image
          <<: [*master_filter, *docker_job]
          tags: "gofunky/docker:${DOCKER_VERSION},gofunky/docker:${DOCKER_VERSION}-compose${COMPOSE_VERSION},gofunky/docker:latest,gofunky/docker:stable,gofunky/docker:daily"
          login: docker login -u $DOCKER_USR -p $DOCKER_PWD
          cache: true
          requires: [set_docker_version, set_compose_version]

      - docker/build_test_push:
          name: build_envload_image
          <<: [*master_filter, *docker_job]
          tags: "gofunky/docker:${DOCKER_VERSION}-envload,gofunky/docker:${DOCKER_VERSION}-compose${COMPOSE_VERSION}-envload,gofunky/docker:envload,gofunky/docker:stable-envload"
          login: docker login -u $DOCKER_USR -p $DOCKER_PWD
          cache: true
          add_labels: false
          path: "./envorb"
          compose: "./envorb/test/docker-compose.test.yml"
          base_tag: dockertest
          args: "BASE=gofunky/docker:${DOCKER_VERSION}-compose${COMPOSE_VERSION}"
          requires: [set_docker_version, set_compose_version, build_latest_image]

  publish_latest_orb:
    jobs:
      - orbtools/check:
          name: check_pull_request
          <<: [*pr_filter, *use_alpine_version]

      - orbtools/env-pack-publish:
          name: publish_latest_orb
          context: orb-tools
          version: "dev:${CIRCLE_BRANCH}"
          <<: [*master_filter, *use_alpine_version]

      - envorb/git_tag:
          name: release_tag
          variable: ORB_PUBLISHING_VERSION
          <<: [*tag_filter, *use_alpine_version]

      - orbtools/env-pack-publish:
          name: publish_release_orb
          context: orb-tools
          <<: [*tag_filter, *use_alpine_version]
          requires: [release_tag]
